<?xml version="1.0" encoding="utf-8"?><Database Name="db_ofc" Class="websqlclassessDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-MHFFI2S;Initial Catalog=db_ofc;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="db_ofcConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="c_id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="c_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cell" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="no_item" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="t_bill" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>