#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3layerweb
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_ofc")]
	public partial class websqlclassessDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public websqlclassessDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db_ofcConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public websqlclassessDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public websqlclassessDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public websqlclassessDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public websqlclassessDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer
	{
		
		private string _c_id;
		
		private string _c_name;
		
		private string _cell;
		
		private string _no_item;
		
		private string _t_bill;
		
		public Customer()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string c_id
		{
			get
			{
				return this._c_id;
			}
			set
			{
				if ((this._c_id != value))
				{
					this._c_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string c_name
		{
			get
			{
				return this._c_name;
			}
			set
			{
				if ((this._c_name != value))
				{
					this._c_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cell
		{
			get
			{
				return this._cell;
			}
			set
			{
				if ((this._cell != value))
				{
					this._cell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_item", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string no_item
		{
			get
			{
				return this._no_item;
			}
			set
			{
				if ((this._no_item != value))
				{
					this._no_item = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_t_bill", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string t_bill
		{
			get
			{
				return this._t_bill;
			}
			set
			{
				if ((this._t_bill != value))
				{
					this._t_bill = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
